# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sermv.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1416, 736)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/orbz-fire-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabMenu = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabMenu.sizePolicy().hasHeightForWidth())
        self.tabMenu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabMenu.setFont(font)
        self.tabMenu.setTabPosition(QtGui.QTabWidget.West)
        self.tabMenu.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabMenu.setElideMode(QtCore.Qt.ElideNone)
        self.tabMenu.setDocumentMode(False)
        self.tabMenu.setTabsClosable(False)
        self.tabMenu.setMovable(False)
        self.tabMenu.setObjectName(_fromUtf8("tabMenu"))
        self.tb_data_monitoring = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_data_monitoring.sizePolicy().hasHeightForWidth())
        self.tb_data_monitoring.setSizePolicy(sizePolicy)
        self.tb_data_monitoring.setObjectName(_fromUtf8("tb_data_monitoring"))
        self.webView = QtWebKit.QWebView(self.tb_data_monitoring)
        self.webView.setGeometry(QtCore.QRect(20, 159, 811, 511))
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.lcdNumber_ffwi = QtGui.QLCDNumber(self.tb_data_monitoring)
        self.lcdNumber_ffwi.setGeometry(QtCore.QRect(480, 40, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcdNumber_ffwi.setFont(font)
        self.lcdNumber_ffwi.setAutoFillBackground(False)
        self.lcdNumber_ffwi.setFrameShape(QtGui.QFrame.Box)
        self.lcdNumber_ffwi.setLineWidth(1)
        self.lcdNumber_ffwi.setMidLineWidth(0)
        self.lcdNumber_ffwi.setSmallDecimalPoint(True)
        self.lcdNumber_ffwi.setNumDigits(3)
        self.lcdNumber_ffwi.setDigitCount(3)
        self.lcdNumber_ffwi.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_ffwi.setProperty("value", 0.0)
        self.lcdNumber_ffwi.setObjectName(_fromUtf8("lcdNumber_ffwi"))
        self.lbl_riskstate = QtGui.QLabel(self.tb_data_monitoring)
        self.lbl_riskstate.setGeometry(QtCore.QRect(20, 40, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_riskstate.setFont(font)
        self.lbl_riskstate.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_riskstate.setFrameShadow(QtGui.QFrame.Sunken)
        self.lbl_riskstate.setLineWidth(1)
        self.lbl_riskstate.setObjectName(_fromUtf8("lbl_riskstate"))
        self.lbl_RiskStateValue = QtGui.QLabel(self.tb_data_monitoring)
        self.lbl_RiskStateValue.setGeometry(QtCore.QRect(120, 40, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_RiskStateValue.setFont(font)
        self.lbl_RiskStateValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lbl_RiskStateValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lbl_RiskStateValue.setText(_fromUtf8(""))
        self.lbl_RiskStateValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_RiskStateValue.setObjectName(_fromUtf8("lbl_RiskStateValue"))
        self.groupBox = QtGui.QGroupBox(self.tb_data_monitoring)
        self.groupBox.setGeometry(QtCore.QRect(850, 60, 451, 621))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 431, 281))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget = QtGui.QWidget(self.gridLayoutWidget)
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.pushButton_predict_risk = QtGui.QPushButton(self.groupBox)
        self.pushButton_predict_risk.setGeometry(QtCore.QRect(250, 370, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_predict_risk.setFont(font)
        self.pushButton_predict_risk.setStyleSheet(_fromUtf8("QPushButton { \n"
"    background-color: #991100; \n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 32px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 20px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"     color: red;\n"
"    background-color: #33AA22;\n"
" }"))
        self.pushButton_predict_risk.setObjectName(_fromUtf8("pushButton_predict_risk"))
        self.txt_mean = QtGui.QLineEdit(self.groupBox)
        self.txt_mean.setGeometry(QtCore.QRect(280, 450, 161, 31))
        self.txt_mean.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_mean.setObjectName(_fromUtf8("txt_mean"))
        self.lbl_premean = QtGui.QLabel(self.groupBox)
        self.lbl_premean.setGeometry(QtCore.QRect(20, 450, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_premean.setFont(font)
        self.lbl_premean.setObjectName(_fromUtf8("lbl_premean"))
        self.dial = QtGui.QDial(self.groupBox)
        self.dial.setGeometry(QtCore.QRect(10, 350, 121, 91))
        self.dial.setAutoFillBackground(False)
        self.dial.setMinimum(0)
        self.dial.setMaximum(12)
        self.dial.setOrientation(QtCore.Qt.Horizontal)
        self.dial.setInvertedAppearance(False)
        self.dial.setInvertedControls(False)
        self.dial.setWrapping(True)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.lbl_dial = QtGui.QLabel(self.groupBox)
        self.lbl_dial.setGeometry(QtCore.QRect(170, 380, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_dial.setFont(font)
        self.lbl_dial.setAutoFillBackground(False)
        self.lbl_dial.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_dial.setObjectName(_fromUtf8("lbl_dial"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 310, 431, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lbl_dialnum = QtGui.QLabel(self.groupBox)
        self.lbl_dialnum.setGeometry(QtCore.QRect(140, 380, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_dialnum.setFont(font)
        self.lbl_dialnum.setObjectName(_fromUtf8("lbl_dialnum"))
        self.lbl_premax = QtGui.QLabel(self.groupBox)
        self.lbl_premax.setGeometry(QtCore.QRect(20, 530, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_premax.setFont(font)
        self.lbl_premax.setObjectName(_fromUtf8("lbl_premax"))
        self.txt_max = QtGui.QLineEdit(self.groupBox)
        self.txt_max.setGeometry(QtCore.QRect(280, 530, 161, 31))
        self.txt_max.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_max.setObjectName(_fromUtf8("txt_max"))
        self.lbl_premiin = QtGui.QLabel(self.groupBox)
        self.lbl_premiin.setGeometry(QtCore.QRect(20, 490, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_premiin.setFont(font)
        self.lbl_premiin.setObjectName(_fromUtf8("lbl_premiin"))
        self.txt_min = QtGui.QLineEdit(self.groupBox)
        self.txt_min.setGeometry(QtCore.QRect(280, 490, 161, 31))
        self.txt_min.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_min.setObjectName(_fromUtf8("txt_min"))
        self.txt_max_2 = QtGui.QLineEdit(self.groupBox)
        self.txt_max_2.setGeometry(QtCore.QRect(280, 570, 161, 31))
        self.txt_max_2.setText(_fromUtf8(""))
        self.txt_max_2.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_max_2.setObjectName(_fromUtf8("txt_max_2"))
        self.lbl_premax_2 = QtGui.QLabel(self.groupBox)
        self.lbl_premax_2.setGeometry(QtCore.QRect(20, 570, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_premax_2.setFont(font)
        self.lbl_premax_2.setObjectName(_fromUtf8("lbl_premax_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.tb_data_monitoring)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 831, 671))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(28, 99, 111, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(240, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(640, 106, 81, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.ln_ctmp = QtGui.QLineEdit(self.groupBox_2)
        self.ln_ctmp.setGeometry(QtCore.QRect(140, 100, 91, 31))
        self.ln_ctmp.setObjectName(_fromUtf8("ln_ctmp"))
        self.ln_relh = QtGui.QLineEdit(self.groupBox_2)
        self.ln_relh.setGeometry(QtCore.QRect(342, 100, 91, 31))
        self.ln_relh.setObjectName(_fromUtf8("ln_relh"))
        self.ln_wndsp = QtGui.QLineEdit(self.groupBox_2)
        self.ln_wndsp.setGeometry(QtCore.QRect(530, 100, 91, 31))
        self.ln_wndsp.setObjectName(_fromUtf8("ln_wndsp"))
        self.ln_wnd = QtGui.QLineEdit(self.groupBox_2)
        self.ln_wnd.setGeometry(QtCore.QRect(722, 100, 91, 31))
        self.ln_wnd.setObjectName(_fromUtf8("ln_wnd"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 80, 811, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(430, 25, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lbl_riskstate_4 = QtGui.QLabel(self.groupBox_2)
        self.lbl_riskstate_4.setGeometry(QtCore.QRect(570, 30, 141, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_riskstate_4.setFont(font)
        self.lbl_riskstate_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_riskstate_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.lbl_riskstate_4.setLineWidth(1)
        self.lbl_riskstate_4.setObjectName(_fromUtf8("lbl_riskstate_4"))
        self.lcdNumber_risk = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_risk.setGeometry(QtCore.QRect(710, 30, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcdNumber_risk.setFont(font)
        self.lcdNumber_risk.setAutoFillBackground(False)
        self.lcdNumber_risk.setFrameShape(QtGui.QFrame.Box)
        self.lcdNumber_risk.setLineWidth(1)
        self.lcdNumber_risk.setMidLineWidth(0)
        self.lcdNumber_risk.setSmallDecimalPoint(False)
        self.lcdNumber_risk.setNumDigits(5)
        self.lcdNumber_risk.setDigitCount(5)
        self.lcdNumber_risk.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_risk.setProperty("value", 0.0)
        self.lcdNumber_risk.setObjectName(_fromUtf8("lcdNumber_risk"))
        self.lbl_risk = QtGui.QLabel(self.groupBox_2)
        self.lbl_risk.setGeometry(QtCore.QRect(250, 30, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_risk.setFont(font)
        self.lbl_risk.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_risk.setFrameShadow(QtGui.QFrame.Sunken)
        self.lbl_risk.setObjectName(_fromUtf8("lbl_risk"))
        self.groupBox_4.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.ln_ctmp.raise_()
        self.ln_relh.raise_()
        self.ln_wndsp.raise_()
        self.ln_wnd.raise_()
        self.lbl_riskstate_4.raise_()
        self.lcdNumber_risk.raise_()
        self.lbl_risk.raise_()
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.tb_data_monitoring)
        self.dateTimeEdit.setEnabled(True)
        self.dateTimeEdit.setGeometry(QtCore.QRect(850, 20, 451, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("OCR A Extended"))
        font.setPointSize(18)
        font.setItalic(False)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setWrapping(False)
        self.dateTimeEdit.setFrame(True)
        self.dateTimeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateTimeEdit.setReadOnly(True)
        self.dateTimeEdit.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit.setAccelerated(True)
        self.dateTimeEdit.setCalendarPopup(False)
        self.dateTimeEdit.setObjectName(_fromUtf8("dateTimeEdit"))
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.webView.raise_()
        self.lcdNumber_ffwi.raise_()
        self.lbl_riskstate.raise_()
        self.lbl_RiskStateValue.raise_()
        self.dateTimeEdit.raise_()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/Letter_M_Icon_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabMenu.addTab(self.tb_data_monitoring, icon1, _fromUtf8(""))
        self.tb_data_view = QtGui.QWidget()
        self.tb_data_view.setObjectName(_fromUtf8("tb_data_view"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tb_data_view)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableView = QtGui.QTableView(self.tb_data_view)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableView.setFont(font)
        self.tableView.setStyleSheet(_fromUtf8("selection-background-color: rgba(252, 168, 0, 150);\n"
"QTableCornerButton::section {\n"
"    background: red;\n"
"    border: 2px outset red;\n"
"}"))
        self.tableView.setFrameShadow(QtGui.QFrame.Sunken)
        self.tableView.setMidLineWidth(0)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView.setSortingEnabled(False)
        self.tableView.setWordWrap(True)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.tableView.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView.horizontalHeader().setDefaultSectionSize(120)
        self.tableView.horizontalHeader().setMinimumSectionSize(70)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setCascadingSectionResizes(False)
        self.tableView.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableView)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/Letter_V_Icon_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabMenu.addTab(self.tb_data_view, icon2, _fromUtf8(""))
        self.tab_data_analysis = QtGui.QWidget()
        self.tab_data_analysis.setObjectName(_fromUtf8("tab_data_analysis"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_data_analysis)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(340, 20, 941, 651))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_DA_plot = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_DA_plot.setObjectName(_fromUtf8("gridLayout_DA_plot"))
        self.widget_scatter = QtGui.QWidget(self.gridLayoutWidget_2)
        self.widget_scatter.setObjectName(_fromUtf8("widget_scatter"))
        self.gridLayout_DA_plot.addWidget(self.widget_scatter, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_data_analysis)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 301, 671))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.pushButton_DA_showplot = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_DA_showplot.setGeometry(QtCore.QRect(30, 584, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_DA_showplot.setFont(font)
        self.pushButton_DA_showplot.setStyleSheet(_fromUtf8(""))
        self.pushButton_DA_showplot.setCheckable(False)
        self.pushButton_DA_showplot.setObjectName(_fromUtf8("pushButton_DA_showplot"))
        self.pushButton_DA_data_consist = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_DA_data_consist.setGeometry(QtCore.QRect(20, 30, 271, 41))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_DA_data_consist.setFont(font)
        self.pushButton_DA_data_consist.setStyleSheet(_fromUtf8(""))
        self.pushButton_DA_data_consist.setObjectName(_fromUtf8("pushButton_DA_data_consist"))
        self.lineEdit_DA_coefficient = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_DA_coefficient.setGeometry(QtCore.QRect(140, 490, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_DA_coefficient.setFont(font)
        self.lineEdit_DA_coefficient.setObjectName(_fromUtf8("lineEdit_DA_coefficient"))
        self.lineEdit_DA_pvalue = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_DA_pvalue.setGeometry(QtCore.QRect(140, 530, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_DA_pvalue.setFont(font)
        self.lineEdit_DA_pvalue.setObjectName(_fromUtf8("lineEdit_DA_pvalue"))
        self.lbl_pvalue = QtGui.QLabel(self.groupBox_3)
        self.lbl_pvalue.setGeometry(QtCore.QRect(40, 530, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_pvalue.setFont(font)
        self.lbl_pvalue.setObjectName(_fromUtf8("lbl_pvalue"))
        self.lbl_coeficient = QtGui.QLabel(self.groupBox_3)
        self.lbl_coeficient.setGeometry(QtCore.QRect(40, 490, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_coeficient.setFont(font)
        self.lbl_coeficient.setObjectName(_fromUtf8("lbl_coeficient"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_8.setGeometry(QtCore.QRect(30, 240, 251, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.radioButton_PM_TMP = QtGui.QRadioButton(self.groupBox_8)
        self.radioButton_PM_TMP.setGeometry(QtCore.QRect(20, 60, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_PM_TMP.setFont(font)
        self.radioButton_PM_TMP.setObjectName(_fromUtf8("radioButton_PM_TMP"))
        self.radioButton_PM_HM = QtGui.QRadioButton(self.groupBox_8)
        self.radioButton_PM_HM.setGeometry(QtCore.QRect(20, 90, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_PM_HM.setFont(font)
        self.radioButton_PM_HM.setObjectName(_fromUtf8("radioButton_PM_HM"))
        self.radioButton_PM_SMK = QtGui.QRadioButton(self.groupBox_8)
        self.radioButton_PM_SMK.setGeometry(QtCore.QRect(20, 120, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_PM_SMK.setFont(font)
        self.radioButton_PM_SMK.setObjectName(_fromUtf8("radioButton_PM_SMK"))
        self.radioButton_PM_WNSPD = QtGui.QRadioButton(self.groupBox_8)
        self.radioButton_PM_WNSPD.setGeometry(QtCore.QRect(20, 150, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_PM_WNSPD.setFont(font)
        self.radioButton_PM_WNSPD.setObjectName(_fromUtf8("radioButton_PM_WNSPD"))
        self.radioButton_PM_FWI = QtGui.QRadioButton(self.groupBox_8)
        self.radioButton_PM_FWI.setGeometry(QtCore.QRect(20, 30, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_PM_FWI.setFont(font)
        self.radioButton_PM_FWI.setChecked(True)
        self.radioButton_PM_FWI.setObjectName(_fromUtf8("radioButton_PM_FWI"))
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 80, 271, 491))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.radioButton_PM_RISK = QtGui.QRadioButton(self.groupBox_9)
        self.radioButton_PM_RISK.setEnabled(False)
        self.radioButton_PM_RISK.setGeometry(QtCore.QRect(20, 130, 150, 25))
        self.radioButton_PM_RISK.setCheckable(True)
        self.radioButton_PM_RISK.setChecked(True)
        self.radioButton_PM_RISK.setObjectName(_fromUtf8("radioButton_PM_RISK"))
        self.pushButton_DA_pearson = QtGui.QPushButton(self.groupBox_9)
        self.pushButton_DA_pearson.setGeometry(QtCore.QRect(10, 360, 251, 41))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_DA_pearson.setFont(font)
        self.pushButton_DA_pearson.setStyleSheet(_fromUtf8(""))
        self.pushButton_DA_pearson.setObjectName(_fromUtf8("pushButton_DA_pearson"))
        self.groupBox_11 = QtGui.QGroupBox(self.groupBox_9)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 30, 251, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_11.setFlat(False)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.radioButton_DA_pears = QtGui.QRadioButton(self.groupBox_11)
        self.radioButton_DA_pears.setGeometry(QtCore.QRect(20, 30, 221, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_DA_pears.setFont(font)
        self.radioButton_DA_pears.setChecked(True)
        self.radioButton_DA_pears.setObjectName(_fromUtf8("radioButton_DA_pears"))
        self.radioButton_DA_spear = QtGui.QRadioButton(self.groupBox_11)
        self.radioButton_DA_spear.setGeometry(QtCore.QRect(20, 60, 221, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_DA_spear.setFont(font)
        self.radioButton_DA_spear.setObjectName(_fromUtf8("radioButton_DA_spear"))
        self.comboBox_DA_diag = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_DA_diag.setGeometry(QtCore.QRect(120, 630, 161, 30))
        self.comboBox_DA_diag.setObjectName(_fromUtf8("comboBox_DA_diag"))
        self.comboBox_DA_diag.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(30, 630, 91, 30))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.groupBox_9.raise_()
        self.pushButton_DA_showplot.raise_()
        self.pushButton_DA_data_consist.raise_()
        self.lineEdit_DA_coefficient.raise_()
        self.lineEdit_DA_pvalue.raise_()
        self.lbl_pvalue.raise_()
        self.lbl_coeficient.raise_()
        self.groupBox_8.raise_()
        self.comboBox_DA_diag.raise_()
        self.label_5.raise_()
        self.groupBox_5 = QtGui.QGroupBox(self.tab_data_analysis)
        self.groupBox_5.setGeometry(QtCore.QRect(320, 10, 981, 671))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.groupBox_5.raise_()
        self.groupBox_3.raise_()
        self.gridLayoutWidget_2.raise_()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/Letter_A_Icon_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabMenu.addTab(self.tab_data_analysis, icon3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.pushButton_PM_H2Oinit = QtGui.QPushButton(self.tab)
        self.pushButton_PM_H2Oinit.setGeometry(QtCore.QRect(30, 40, 391, 41))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_PM_H2Oinit.setFont(font)
        self.pushButton_PM_H2Oinit.setStyleSheet(_fromUtf8(""))
        self.pushButton_PM_H2Oinit.setObjectName(_fromUtf8("pushButton_PM_H2Oinit"))
        self.lineEdit_PM_h2o_response = QtGui.QLineEdit(self.tab)
        self.lineEdit_PM_h2o_response.setGeometry(QtCore.QRect(30, 90, 391, 31))
        self.lineEdit_PM_h2o_response.setAutoFillBackground(False)
        self.lineEdit_PM_h2o_response.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PM_h2o_response.setReadOnly(True)
        self.lineEdit_PM_h2o_response.setObjectName(_fromUtf8("lineEdit_PM_h2o_response"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 431, 671))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.lineEdit_PM_RMSE = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_PM_RMSE.setGeometry(QtCore.QRect(240, 560, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_PM_RMSE.setFont(font)
        self.lineEdit_PM_RMSE.setReadOnly(True)
        self.lineEdit_PM_RMSE.setObjectName(_fromUtf8("lineEdit_PM_RMSE"))
        self.label_PM_MSE = QtGui.QLabel(self.groupBox_6)
        self.label_PM_MSE.setGeometry(QtCore.QRect(40, 530, 171, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_PM_MSE.setFont(font)
        self.label_PM_MSE.setObjectName(_fromUtf8("label_PM_MSE"))
        self.label_PM_RMSE = QtGui.QLabel(self.groupBox_6)
        self.label_PM_RMSE.setGeometry(QtCore.QRect(40, 560, 191, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_PM_RMSE.setFont(font)
        self.label_PM_RMSE.setObjectName(_fromUtf8("label_PM_RMSE"))
        self.label_PM_MAE = QtGui.QLabel(self.groupBox_6)
        self.label_PM_MAE.setGeometry(QtCore.QRect(40, 620, 191, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_PM_MAE.setFont(font)
        self.label_PM_MAE.setObjectName(_fromUtf8("label_PM_MAE"))
        self.label_PM_MRD = QtGui.QLabel(self.groupBox_6)
        self.label_PM_MRD.setGeometry(QtCore.QRect(40, 590, 201, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_PM_MRD.setFont(font)
        self.label_PM_MRD.setObjectName(_fromUtf8("label_PM_MRD"))
        self.lineEdit_PM_MAE = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_PM_MAE.setGeometry(QtCore.QRect(240, 620, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_PM_MAE.setFont(font)
        self.lineEdit_PM_MAE.setReadOnly(True)
        self.lineEdit_PM_MAE.setObjectName(_fromUtf8("lineEdit_PM_MAE"))
        self.lineEdit_PM_MRD = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_PM_MRD.setGeometry(QtCore.QRect(240, 590, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_PM_MRD.setFont(font)
        self.lineEdit_PM_MRD.setReadOnly(True)
        self.lineEdit_PM_MRD.setObjectName(_fromUtf8("lineEdit_PM_MRD"))
        self.tabWidget_PM_Estimator = QtGui.QTabWidget(self.groupBox_6)
        self.tabWidget_PM_Estimator.setGeometry(QtCore.QRect(20, 120, 391, 285))
        self.tabWidget_PM_Estimator.setObjectName(_fromUtf8("tabWidget_PM_Estimator"))
        self.tab_DL = QtGui.QWidget()
        self.tab_DL.setObjectName(_fromUtf8("tab_DL"))
        self.tab_PM_Distribution = QtGui.QLabel(self.tab_DL)
        self.tab_PM_Distribution.setGeometry(QtCore.QRect(20, 10, 101, 25))
        self.tab_PM_Distribution.setObjectName(_fromUtf8("tab_PM_Distribution"))
        self.tab_PM_Activation = QtGui.QLabel(self.tab_DL)
        self.tab_PM_Activation.setGeometry(QtCore.QRect(20, 40, 141, 25))
        self.tab_PM_Activation.setObjectName(_fromUtf8("tab_PM_Activation"))
        self.tab_PM_Epochs = QtGui.QLabel(self.tab_DL)
        self.tab_PM_Epochs.setGeometry(QtCore.QRect(20, 130, 71, 25))
        self.tab_PM_Epochs.setObjectName(_fromUtf8("tab_PM_Epochs"))
        self.tab_PM_Hidden = QtGui.QLabel(self.tab_DL)
        self.tab_PM_Hidden.setGeometry(QtCore.QRect(20, 100, 121, 25))
        self.tab_PM_Hidden.setObjectName(_fromUtf8("tab_PM_Hidden"))
        self.comboBox_PM_distribution = QtGui.QComboBox(self.tab_DL)
        self.comboBox_PM_distribution.setGeometry(QtCore.QRect(150, 10, 221, 25))
        self.comboBox_PM_distribution.setObjectName(_fromUtf8("comboBox_PM_distribution"))
        self.comboBox_PM_distribution.addItem(_fromUtf8(""))
        self.comboBox_PM_distribution.addItem(_fromUtf8(""))
        self.comboBox_PM_distribution.addItem(_fromUtf8(""))
        self.comboBox_PM_distribution.addItem(_fromUtf8(""))
        self.comboBox_PM_distribution.addItem(_fromUtf8(""))
        self.comboBox_PM_distribution.addItem(_fromUtf8(""))
        self.comboBox_PM_distribution.addItem(_fromUtf8(""))
        self.comboBox_PM_distribution.addItem(_fromUtf8(""))
        self.comboBox_PM_distribution.addItem(_fromUtf8(""))
        self.comboBox_PM_activation = QtGui.QComboBox(self.tab_DL)
        self.comboBox_PM_activation.setGeometry(QtCore.QRect(150, 40, 221, 25))
        self.comboBox_PM_activation.setObjectName(_fromUtf8("comboBox_PM_activation"))
        self.comboBox_PM_activation.addItem(_fromUtf8(""))
        self.comboBox_PM_activation.addItem(_fromUtf8(""))
        self.comboBox_PM_activation.addItem(_fromUtf8(""))
        self.comboBox_PM_activation.addItem(_fromUtf8(""))
        self.comboBox_PM_activation.addItem(_fromUtf8(""))
        self.comboBox_PM_activation.addItem(_fromUtf8(""))
        self.comboBox_PM_hidden = QtGui.QComboBox(self.tab_DL)
        self.comboBox_PM_hidden.setGeometry(QtCore.QRect(150, 100, 221, 25))
        self.comboBox_PM_hidden.setObjectName(_fromUtf8("comboBox_PM_hidden"))
        self.comboBox_PM_hidden.addItem(_fromUtf8(""))
        self.comboBox_PM_hidden.addItem(_fromUtf8(""))
        self.comboBox_PM_hidden.addItem(_fromUtf8(""))
        self.comboBox_PM_hidden.addItem(_fromUtf8(""))
        self.comboBox_PM_loss = QtGui.QComboBox(self.tab_DL)
        self.comboBox_PM_loss.setGeometry(QtCore.QRect(150, 70, 221, 25))
        self.comboBox_PM_loss.setObjectName(_fromUtf8("comboBox_PM_loss"))
        self.comboBox_PM_loss.addItem(_fromUtf8(""))
        self.comboBox_PM_loss.addItem(_fromUtf8(""))
        self.comboBox_PM_loss.addItem(_fromUtf8(""))
        self.comboBox_PM_loss.addItem(_fromUtf8(""))
        self.comboBox_PM_loss.addItem(_fromUtf8(""))
        self.tab_PM_Loss = QtGui.QLabel(self.tab_DL)
        self.tab_PM_Loss.setGeometry(QtCore.QRect(20, 70, 121, 25))
        self.tab_PM_Loss.setObjectName(_fromUtf8("tab_PM_Loss"))
        self.comboBox_PM_sparse = QtGui.QComboBox(self.tab_DL)
        self.comboBox_PM_sparse.setGeometry(QtCore.QRect(150, 160, 221, 25))
        self.comboBox_PM_sparse.setObjectName(_fromUtf8("comboBox_PM_sparse"))
        self.comboBox_PM_sparse.addItem(_fromUtf8(""))
        self.comboBox_PM_sparse.addItem(_fromUtf8(""))
        self.tab_PM_Sparse = QtGui.QLabel(self.tab_DL)
        self.tab_PM_Sparse.setGeometry(QtCore.QRect(20, 160, 71, 25))
        self.tab_PM_Sparse.setObjectName(_fromUtf8("tab_PM_Sparse"))
        self.comboBox_PM_shuffle = QtGui.QComboBox(self.tab_DL)
        self.comboBox_PM_shuffle.setGeometry(QtCore.QRect(150, 190, 221, 25))
        self.comboBox_PM_shuffle.setObjectName(_fromUtf8("comboBox_PM_shuffle"))
        self.comboBox_PM_shuffle.addItem(_fromUtf8(""))
        self.comboBox_PM_shuffle.addItem(_fromUtf8(""))
        self.tab_PM_shuffle = QtGui.QLabel(self.tab_DL)
        self.tab_PM_shuffle.setGeometry(QtCore.QRect(20, 190, 121, 25))
        self.tab_PM_shuffle.setObjectName(_fromUtf8("tab_PM_shuffle"))
        self.tab_PM_L1 = QtGui.QLabel(self.tab_DL)
        self.tab_PM_L1.setGeometry(QtCore.QRect(20, 220, 51, 25))
        self.tab_PM_L1.setObjectName(_fromUtf8("tab_PM_L1"))
        self.tab_PM_L2 = QtGui.QLabel(self.tab_DL)
        self.tab_PM_L2.setGeometry(QtCore.QRect(200, 220, 51, 25))
        self.tab_PM_L2.setObjectName(_fromUtf8("tab_PM_L2"))
        self.doubleSpinBox_PM_L1 = QtGui.QDoubleSpinBox(self.tab_DL)
        self.doubleSpinBox_PM_L1.setGeometry(QtCore.QRect(70, 220, 121, 25))
        self.doubleSpinBox_PM_L1.setDecimals(1)
        self.doubleSpinBox_PM_L1.setSingleStep(0.1)
        self.doubleSpinBox_PM_L1.setObjectName(_fromUtf8("doubleSpinBox_PM_L1"))
        self.doubleSpinBox_PM_L2 = QtGui.QDoubleSpinBox(self.tab_DL)
        self.doubleSpinBox_PM_L2.setGeometry(QtCore.QRect(250, 220, 121, 25))
        self.doubleSpinBox_PM_L2.setDecimals(1)
        self.doubleSpinBox_PM_L2.setMaximum(100.0)
        self.doubleSpinBox_PM_L2.setSingleStep(0.1)
        self.doubleSpinBox_PM_L2.setObjectName(_fromUtf8("doubleSpinBox_PM_L2"))
        self.spinBox_PM_epochs = QtGui.QDoubleSpinBox(self.tab_DL)
        self.spinBox_PM_epochs.setGeometry(QtCore.QRect(150, 130, 221, 25))
        self.spinBox_PM_epochs.setDecimals(0)
        self.spinBox_PM_epochs.setMaximum(10000.0)
        self.spinBox_PM_epochs.setSingleStep(10.0)
        self.spinBox_PM_epochs.setProperty("value", 10.0)
        self.spinBox_PM_epochs.setObjectName(_fromUtf8("spinBox_PM_epochs"))
        self.tabWidget_PM_Estimator.addTab(self.tab_DL, _fromUtf8(""))
        self.pushButton_PM_BuildModel = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_PM_BuildModel.setGeometry(QtCore.QRect(20, 410, 391, 41))
        self.pushButton_PM_BuildModel.setObjectName(_fromUtf8("pushButton_PM_BuildModel"))
        self.groupBox_10 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 490, 391, 171))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.lineEdit_PM_MSE = QtGui.QLineEdit(self.groupBox_10)
        self.lineEdit_PM_MSE.setGeometry(QtCore.QRect(220, 40, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_PM_MSE.setFont(font)
        self.lineEdit_PM_MSE.setReadOnly(True)
        self.lineEdit_PM_MSE.setObjectName(_fromUtf8("lineEdit_PM_MSE"))
        self.progressBar = QtGui.QProgressBar(self.groupBox_6)
        self.progressBar.setGeometry(QtCore.QRect(110, 460, 301, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.label_7 = QtGui.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(30, 460, 81, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.groupBox_10.raise_()
        self.lineEdit_PM_RMSE.raise_()
        self.label_PM_MSE.raise_()
        self.label_PM_RMSE.raise_()
        self.label_PM_MAE.raise_()
        self.label_PM_MRD.raise_()
        self.lineEdit_PM_MAE.raise_()
        self.lineEdit_PM_MRD.raise_()
        self.tabWidget_PM_Estimator.raise_()
        self.pushButton_PM_BuildModel.raise_()
        self.progressBar.raise_()
        self.label_7.raise_()
        self.label_PM_hum = QtGui.QLabel(self.tab)
        self.label_PM_hum.setGeometry(QtCore.QRect(800, 40, 101, 21))
        self.label_PM_hum.setObjectName(_fromUtf8("label_PM_hum"))
        self.label_PM_wndspd = QtGui.QLabel(self.tab)
        self.label_PM_wndspd.setGeometry(QtCore.QRect(930, 40, 131, 21))
        self.label_PM_wndspd.setObjectName(_fromUtf8("label_PM_wndspd"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(460, 10, 841, 671))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.pushButton_PM_LastWData = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_PM_LastWData.setGeometry(QtCore.QRect(20, 150, 231, 41))
        self.pushButton_PM_LastWData.setStyleSheet(_fromUtf8(""))
        self.pushButton_PM_LastWData.setObjectName(_fromUtf8("pushButton_PM_LastWData"))
        self.doubleSpinBox_PM_smoke = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_PM_smoke.setGeometry(QtCore.QRect(20, 60, 141, 31))
        self.doubleSpinBox_PM_smoke.setDecimals(2)
        self.doubleSpinBox_PM_smoke.setMaximum(10000.0)
        self.doubleSpinBox_PM_smoke.setSingleStep(100.0)
        self.doubleSpinBox_PM_smoke.setObjectName(_fromUtf8("doubleSpinBox_PM_smoke"))
        self.doubleSpinBox_PM_temp = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_PM_temp.setGeometry(QtCore.QRect(170, 60, 141, 31))
        self.doubleSpinBox_PM_temp.setObjectName(_fromUtf8("doubleSpinBox_PM_temp"))
        self.doubleSpinBox_PM_humidity = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_PM_humidity.setGeometry(QtCore.QRect(320, 60, 141, 31))
        self.doubleSpinBox_PM_humidity.setObjectName(_fromUtf8("doubleSpinBox_PM_humidity"))
        self.doubleSpinBox_PM_WindSpeed = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_PM_WindSpeed.setGeometry(QtCore.QRect(470, 60, 141, 31))
        self.doubleSpinBox_PM_WindSpeed.setObjectName(_fromUtf8("doubleSpinBox_PM_WindSpeed"))
        self.dateTimeEdit_PM_datetime = QtGui.QDateTimeEdit(self.groupBox_7)
        self.dateTimeEdit_PM_datetime.setGeometry(QtCore.QRect(620, 60, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateTimeEdit_PM_datetime.setFont(font)
        self.dateTimeEdit_PM_datetime.setAlignment(QtCore.Qt.AlignCenter)
        self.dateTimeEdit_PM_datetime.setObjectName(_fromUtf8("dateTimeEdit_PM_datetime"))
        self.pushButton_PM_Predict = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_PM_Predict.setGeometry(QtCore.QRect(460, 100, 161, 41))
        self.pushButton_PM_Predict.setStyleSheet(_fromUtf8(""))
        self.pushButton_PM_Predict.setObjectName(_fromUtf8("pushButton_PM_Predict"))
        self.lineEdit_PM_predictRiskVal = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_PM_predictRiskVal.setGeometry(QtCore.QRect(640, 100, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_PM_predictRiskVal.setFont(font)
        self.lineEdit_PM_predictRiskVal.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PM_predictRiskVal.setObjectName(_fromUtf8("lineEdit_PM_predictRiskVal"))
        self.tableView_PM = QtGui.QTableView(self.groupBox_7)
        self.tableView_PM.setGeometry(QtCore.QRect(20, 200, 801, 461))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableView_PM.setFont(font)
        self.tableView_PM.setStyleSheet(_fromUtf8("selection-background-color: rgba(252, 168, 0, 150);\n"
"QTableCornerButton::section {\n"
"    background: red;\n"
"    border: 2px outset red;\n"
"}"))
        self.tableView_PM.setDragEnabled(True)
        self.tableView_PM.setAlternatingRowColors(True)
        self.tableView_PM.setSortingEnabled(False)
        self.tableView_PM.setObjectName(_fromUtf8("tableView_PM"))
        self.pushButton_PM_addRecord = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_PM_addRecord.setGeometry(QtCore.QRect(260, 150, 261, 41))
        self.pushButton_PM_addRecord.setStyleSheet(_fromUtf8(""))
        self.pushButton_PM_addRecord.setObjectName(_fromUtf8("pushButton_PM_addRecord"))
        self.label_PM_smoke = QtGui.QLabel(self.groupBox_7)
        self.label_PM_smoke.setGeometry(QtCore.QRect(50, 30, 101, 21))
        self.label_PM_smoke.setObjectName(_fromUtf8("label_PM_smoke"))
        self.label_PM_temp = QtGui.QLabel(self.groupBox_7)
        self.label_PM_temp.setGeometry(QtCore.QRect(180, 30, 121, 21))
        self.label_PM_temp.setObjectName(_fromUtf8("label_PM_temp"))
        self.label_12 = QtGui.QLabel(self.groupBox_7)
        self.label_12.setGeometry(QtCore.QRect(670, 30, 81, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton_PM_FWI = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_PM_FWI.setGeometry(QtCore.QRect(20, 100, 231, 41))
        self.pushButton_PM_FWI.setStyleSheet(_fromUtf8(""))
        self.pushButton_PM_FWI.setObjectName(_fromUtf8("pushButton_PM_FWI"))
        self.lineEdit_PM_calcFWI = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_PM_calcFWI.setGeometry(QtCore.QRect(260, 100, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_PM_calcFWI.setFont(font)
        self.lineEdit_PM_calcFWI.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PM_calcFWI.setObjectName(_fromUtf8("lineEdit_PM_calcFWI"))
        self.pushButton_PM_addweatherRecord = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_PM_addweatherRecord.setGeometry(QtCore.QRect(530, 150, 291, 41))
        self.pushButton_PM_addweatherRecord.setStyleSheet(_fromUtf8(""))
        self.pushButton_PM_addweatherRecord.setObjectName(_fromUtf8("pushButton_PM_addweatherRecord"))
        self.groupBox_7.raise_()
        self.groupBox_6.raise_()
        self.pushButton_PM_H2Oinit.raise_()
        self.lineEdit_PM_h2o_response.raise_()
        self.label_PM_hum.raise_()
        self.label_PM_wndspd.raise_()
        self.tabMenu.addTab(self.tab, icon1, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabMenu, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionNew = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionNew.setFont(font)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))

        self.retranslateUi(MainWindow)
        self.tabMenu.setCurrentIndex(0)
        self.tabWidget_PM_Estimator.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "iSERM - Intelligent Decision Support System for Environmental Risk Management", None))
        self.lbl_riskstate.setText(_translate("MainWindow", "STATE :", None))
        self.groupBox.setTitle(_translate("MainWindow", "Linear Regression [ Risk ~ RecId ]", None))
        self.pushButton_predict_risk.setText(_translate("MainWindow", "Predict Risk", None))
        self.lbl_premean.setText(_translate("MainWindow", "Predicted mean risk value is :", None))
        self.lbl_dial.setText(_translate("MainWindow", "hours", None))
        self.label_6.setText(_translate("MainWindow", "Dial to hours from now to predict the future risk", None))
        self.lbl_dialnum.setText(_translate("MainWindow", "0", None))
        self.lbl_premax.setText(_translate("MainWindow", "Predicted max risk value is :", None))
        self.lbl_premiin.setText(_translate("MainWindow", "Predicted min risk value is :", None))
        self.lbl_premax_2.setText(_translate("MainWindow", "Predicted risk state is :", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Monitoring Transmitted Data", None))
        self.label.setText(_translate("MainWindow", "Temperature", None))
        self.label_2.setText(_translate("MainWindow", "Rel Humidity", None))
        self.label_4.setText(_translate("MainWindow", "Wind Dir", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Current weather conditions in Tripolis", None))
        self.label_3.setText(_translate("MainWindow", "Wind (kph)", None))
        self.lbl_riskstate_4.setText(_translate("MainWindow", "FIRE RISK :", None))
        self.lbl_risk.setText(_translate("MainWindow", "FOSBERG INDEX :", None))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.tb_data_monitoring), _translate("MainWindow", "Monitor Transmitted Data", None))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.tb_data_view), _translate("MainWindow", "Data View", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Data Analysis", None))
        self.pushButton_DA_showplot.setText(_translate("MainWindow", "Scatter Plot Matrix", None))
        self.pushButton_DA_data_consist.setText(_translate("MainWindow", "Data Consistency Check", None))
        self.lbl_pvalue.setText(_translate("MainWindow", "P-value :", None))
        self.lbl_coeficient.setText(_translate("MainWindow", "Coefficient :", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Risk Over [ Select Variable ]", None))
        self.radioButton_PM_TMP.setText(_translate("MainWindow", "Temperature", None))
        self.radioButton_PM_HM.setText(_translate("MainWindow", "Humidity", None))
        self.radioButton_PM_SMK.setText(_translate("MainWindow", "Smoke", None))
        self.radioButton_PM_WNSPD.setText(_translate("MainWindow", "Windspeed", None))
        self.radioButton_PM_FWI.setText(_translate("MainWindow", "Fosberg Index", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Risk Correlation Calculation", None))
        self.radioButton_PM_RISK.setText(_translate("MainWindow", "Fire Risk", None))
        self.pushButton_DA_pearson.setText(_translate("MainWindow", "Calculate correlation factors", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Select Corellation Method", None))
        self.radioButton_DA_pears.setText(_translate("MainWindow", "Pearson", None))
        self.radioButton_DA_spear.setText(_translate("MainWindow", "Spearman", None))
        self.comboBox_DA_diag.setItemText(0, _translate("MainWindow", "Histogram", None))
        self.label_5.setText(_translate("MainWindow", "Diagonal :", None))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.tab_data_analysis), _translate("MainWindow", "Data Analysis", None))
        self.pushButton_PM_H2Oinit.setText(_translate("MainWindow", "H2O Initialization ", None))
        self.lineEdit_PM_h2o_response.setText(_translate("MainWindow", "[ H2O Server Response ]", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Deep Learning Settings", None))
        self.label_PM_MSE.setText(_translate("MainWindow", "Mean Squared Error :", None))
        self.label_PM_RMSE.setText(_translate("MainWindow", "Root Mean Square Error :", None))
        self.label_PM_MAE.setText(_translate("MainWindow", "Mean Absolute Error :", None))
        self.label_PM_MRD.setText(_translate("MainWindow", "Mean Residual Deviance :", None))
        self.tab_PM_Distribution.setText(_translate("MainWindow", "Distribution :", None))
        self.tab_PM_Activation.setText(_translate("MainWindow", "Activation :", None))
        self.tab_PM_Epochs.setText(_translate("MainWindow", "Epochs :", None))
        self.tab_PM_Hidden.setText(_translate("MainWindow", "Hidden Layers :", None))
        self.comboBox_PM_distribution.setItemText(0, _translate("MainWindow", "gaussian", None))
        self.comboBox_PM_distribution.setItemText(1, _translate("MainWindow", "quantile", None))
        self.comboBox_PM_distribution.setItemText(2, _translate("MainWindow", "poison", None))
        self.comboBox_PM_distribution.setItemText(3, _translate("MainWindow", "huber", None))
        self.comboBox_PM_distribution.setItemText(4, _translate("MainWindow", "bernoulli", None))
        self.comboBox_PM_distribution.setItemText(5, _translate("MainWindow", "multinomial", None))
        self.comboBox_PM_distribution.setItemText(6, _translate("MainWindow", "gamma", None))
        self.comboBox_PM_distribution.setItemText(7, _translate("MainWindow", "laplace", None))
        self.comboBox_PM_distribution.setItemText(8, _translate("MainWindow", "tweedie", None))
        self.comboBox_PM_activation.setItemText(0, _translate("MainWindow", "Rectifier", None))
        self.comboBox_PM_activation.setItemText(1, _translate("MainWindow", "RectifierWithDropout", None))
        self.comboBox_PM_activation.setItemText(2, _translate("MainWindow", "Tanh", None))
        self.comboBox_PM_activation.setItemText(3, _translate("MainWindow", "TanhWithDropout", None))
        self.comboBox_PM_activation.setItemText(4, _translate("MainWindow", "Maxout", None))
        self.comboBox_PM_activation.setItemText(5, _translate("MainWindow", "MaxoutWithDropout", None))
        self.comboBox_PM_hidden.setItemText(0, _translate("MainWindow", "[32,32,32]", None))
        self.comboBox_PM_hidden.setItemText(1, _translate("MainWindow", "[50,50,50]", None))
        self.comboBox_PM_hidden.setItemText(2, _translate("MainWindow", "[100,100,100]", None))
        self.comboBox_PM_hidden.setItemText(3, _translate("MainWindow", "[200,200,200]", None))
        self.comboBox_PM_loss.setItemText(0, _translate("MainWindow", "Quantile", None))
        self.comboBox_PM_loss.setItemText(1, _translate("MainWindow", "Quadratic", None))
        self.comboBox_PM_loss.setItemText(2, _translate("MainWindow", "CrossEntropy", None))
        self.comboBox_PM_loss.setItemText(3, _translate("MainWindow", "Huber", None))
        self.comboBox_PM_loss.setItemText(4, _translate("MainWindow", "Absolute", None))
        self.tab_PM_Loss.setText(_translate("MainWindow", "Loss Function :", None))
        self.comboBox_PM_sparse.setItemText(0, _translate("MainWindow", "False", None))
        self.comboBox_PM_sparse.setItemText(1, _translate("MainWindow", "True", None))
        self.tab_PM_Sparse.setText(_translate("MainWindow", "Sparse :", None))
        self.comboBox_PM_shuffle.setItemText(0, _translate("MainWindow", "False", None))
        self.comboBox_PM_shuffle.setItemText(1, _translate("MainWindow", "True", None))
        self.tab_PM_shuffle.setText(_translate("MainWindow", "Shuffle data :", None))
        self.tab_PM_L1.setText(_translate("MainWindow", "L1 :", None))
        self.tab_PM_L2.setText(_translate("MainWindow", "L2 :", None))
        self.tabWidget_PM_Estimator.setTabText(self.tabWidget_PM_Estimator.indexOf(self.tab_DL), _translate("MainWindow", "Deep Learning", None))
        self.pushButton_PM_BuildModel.setText(_translate("MainWindow", "Build Selected Predictive Data Mining Model", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Model Performance", None))
        self.label_7.setText(_translate("MainWindow", "Progress :", None))
        self.label_PM_hum.setText(_translate("MainWindow", "Humidity(%)", None))
        self.label_PM_wndspd.setText(_translate("MainWindow", "Windspeed(m/sec)", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Risk Prediction", None))
        self.pushButton_PM_LastWData.setText(_translate("MainWindow", "Get Last Weather Data Record", None))
        self.pushButton_PM_Predict.setText(_translate("MainWindow", "Predict Risk", None))
        self.pushButton_PM_addRecord.setText(_translate("MainWindow", "Add Record to Prediction\'s table", None))
        self.label_PM_smoke.setText(_translate("MainWindow", "Smoke(ppm)", None))
        self.label_PM_temp.setText(_translate("MainWindow", "Temperature(C)", None))
        self.label_12.setText(_translate("MainWindow", "DateTime", None))
        self.pushButton_PM_FWI.setText(_translate("MainWindow", "Calculate Fosberg Index", None))
        self.pushButton_PM_addweatherRecord.setText(_translate("MainWindow", "Add Record to Weather data Records", None))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.tab), _translate("MainWindow", "Predictive Models", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))

from PyQt4 import QtWebKit
import rc
